version: 2

formats: all

build:
  os: ubuntu-22.04
  apt_packages:
    - default-jdk
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt