version: 2

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - bash ./scripts/docs/plantuml_server.install.sh

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt