version: "3.8"
# Optional Jupyter Notebook service
services:
  jupyter_notebook:
    image: "cosim-jupyter:latest"
    container_name: ${CONTAINER_NAME:-jupyter_notebook}
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      GRANT_SUDO: "yes"
      SIM_HOST: ${SIM_HOST}
      SIM_USER: ${SIM_USER}
      MONGO_HOST: ${MONGO_HOST}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "8888:8888"
    volumes:
      - ${AIRFLOW_PROJ_DIR}:/home/jovyan/work
    depends_on:
      - database
    links:
      - database
    networks:
      - sim_net

  database:
    image: "postgres:13"
    container_name: ${CONTAINER_NAME:-database}
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_DB: "${COSIM_DB}"
      POSTGRES_USER: "${COSIM_USER}"
      POSTGRES_PASSWORD: "${COSIM_PASSWORD}"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${COSIM_USER}",
          "-d",
          "${COSIM_DB}"
        ]
      interval: 5s
      retries: 5
    restart: always
    volumes:
      - cu_postgres:/var/lib/postgresql/data
      - $STACK_DIR/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sim_net

  mongodb:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    container_name: ${CONTAINER_NAME:-mongodb}
    ports:
      - "27017:27017"
    expose:
      - "27017"
    environment:
      MONGO_INITDB_DATABASE: "${COSIM_DB}"
      MONGODB_INITDB_ROOT_USERNAME: "${MONGODB_INITDB_ROOT_USERNAME}"
      MONGODB_INITDB_ROOT_PASSWORD: "${MONGODB_INITDB_ROOT_PASSWORD}"
    volumes:
      - cu_mongo:/data/db
      - $STACK_DIR/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - sim_net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ${CONTAINER_NAME:-pgadmin}
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    networks:
      - sim_net

volumes:
  cu_mongo: null
  cu_postgres: null

# Create a custom network for bridging the containers
networks:
  sim_net: null