{
 "title": "Helics Example Default",
 "time": { "from": "2023-01-01T00:00:00.000Z", "to": "2023-01-02T00:00:00.000Z" },
 "panels": [
  {
   "title": "EV1 Current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "SELECT * FROM helicsexampledefaultanalysis.hdt_double WHERE federate='Battery' and data_name='Battery/EV1_current'"
    }
   ]
  },
  {
   "title": "EV1 Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT * FROM helicsexampledefaultanalysis.hdt_double WHERE federate='Charger' and data_name='Charger/EV1_voltage'"
    }
   ]
  },
  {
   "title": "EV2 Current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT * FROM helicsexampledefaultanalysis.hdt_double WHERE federate='Battery' and data_name='Battery/EV2_current'"
    }
   ]
  },
  {
   "title": "EV2 Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT * FROM helicsexampledefaultanalysis.hdt_double WHERE federate='Charger' and data_name='Charger/EV2_voltage'"
    }
   ]
  },
  {
   "title": "EV3 Current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT * FROM helicsexampledefaultanalysis.hdt_double WHERE federate='Battery' and data_name='Battery/EV3_current'"
    }
   ]
  },
  {
   "title": "EV3 Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT * FROM helicsexampledefaultanalysis.hdt_double WHERE federate='Charger' and data_name='Charger/EV3_voltage'"
    }
   ]
  },
  {
   "title": "EV4 Current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT * FROM helicsexampledefaultanalysis.hdt_double WHERE federate='Battery' and data_name='Battery/EV4_current'"
    }
   ]
  },
  {
   "title": "EV4 Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT * FROM helicsexampledefaultanalysis.hdt_double WHERE federate='Charger' and data_name='Charger/EV4_voltage'"
    }
   ]
  },
  {
   "title": "EV5 Current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT * FROM helicsexampledefaultanalysis.hdt_double WHERE federate='Battery' and data_name='Battery/EV5_current'"
    }
   ]
  },
  {
   "title": "EV5 Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT * FROM helicsexampledefaultanalysis.hdt_double WHERE federate='Charger' and data_name='Charger/EV5_voltage'"
    }
   ]
  }
 ]
}