
@startuml


participant main
participant federate

main -> federate: <<create>>
activate federate
main -> federate: create_federate()
federate -> federate: create_metadata_manager()
federate -> metadata_manager: <<create>>
activate metadata_manager #Blue
metadata_manager -> metadata_manager: connect()
metadata_manager -> metadata_manager: read_scenario()
metadata_manager -> metadata_manager: read_federation()
deactivate metadata_manager
federate -> federate: set_metadata()
federate -> federate: get_helics_config()
federate -> federate: create_timeseries_manager()
federate -> timeseries_manager: <<create>>
activate timeseries_manager #Green
timeseries_manager -> timeseries_manager: connect()
deactivate timeseries_manager
federate -> federate: create_helics_fed()
deactivate federate

main -> federate: run_cosim_loop()
activate federate
federate -> federate: on_start()
federate -> federate: enter_initialization()
federate -> federate: on_enter_initialization_mode()
federate -> federate: enter_executing_mode()
federate -> federate: on_enter_executing_mode()
federate -> federate: simulate_next_step()
activate federate #Gray
federate -> federate: calculate_next_requested_time()
federate -> federate: request_time()
federate -> federate: get_data_from_federation()
federate -> federate: update_internal_model()
federate -> federate: send_data_to_federation()
federate -> federate : write_to_logger()
deactivate federate
main -> federate: destroy_federate
activate federate
federate -> metadata_manager
activate metadata_manager #Blue
metadata_manager -> metadata_manager: disconnect()
deactivate metadata_manager
federate -> timeseries_manager
activate timeseries_manager #Green
timeseries_manager -> timeseries_manager: flush()
timeseries_manager -> timeseries_manager: disconnect()
deactivate timeseries_manager

@enduml