services:
  helics:
    image: "cosim-cst:latest"
    environment:
      CST_HOST: "ecomp-thrust-3-sandbox"
      LOCAL_USER: "gray570"
      POSTGRES_HOST: "ecomp-thrust-3-sandbox"
      MONGO_HOST: "mongodb://ecomp-thrust-3-sandbox"
      MONGO_PORT: "27017"
    user: worker
    working_dir: /home/worker/case
    volumes:
      - .:/home/worker/case
      - ../../../data:/home/worker/tesp/data
    networks:
      cst_net:
        ipv4_address: 10.5.0.2
    command: /bin/bash -c "exec helics_broker --ipv4 -f 3 --loglevel=warning --name=broker"
  Battery:
    image: "cosim-cst:latest"
    environment:
      CST_HOST: "ecomp-thrust-3-sandbox"
      LOCAL_USER: "gray570"
      POSTGRES_HOST: "ecomp-thrust-3-sandbox"
      MONGO_HOST: "mongodb://ecomp-thrust-3-sandbox"
      MONGO_PORT: "27017"
    user: worker
    working_dir: /home/worker/case
    volumes:
      - .:/home/worker/case
      - ../../../data:/home/worker/tesp/data
    networks:
      cst_net:
        ipv4_address: 10.5.0.3
    command: /bin/bash -c "source /home/worker/venv/bin/activate && exec python3 battery.py"
  Charger:
    image: "cosim-cst:latest"
    environment:
      CST_HOST: "ecomp-thrust-3-sandbox"
      LOCAL_USER: "gray570"
      POSTGRES_HOST: "ecomp-thrust-3-sandbox"
      MONGO_HOST: "mongodb://ecomp-thrust-3-sandbox"
      MONGO_PORT: "27017"
    user: worker
    working_dir: /home/worker/case
    volumes:
      - .:/home/worker/case
      - ../../../data:/home/worker/tesp/data
    networks:
      cst_net:
        ipv4_address: 10.5.0.4
    command: /bin/bash -c "source /home/worker/venv/bin/activate && exec python3 charger.py"
  cosim_logger:
    image: "cosim-cst:latest"
    environment:
      CST_HOST: "ecomp-thrust-3-sandbox"
      LOCAL_USER: "gray570"
      POSTGRES_HOST: "ecomp-thrust-3-sandbox"
      MONGO_HOST: "mongodb://ecomp-thrust-3-sandbox"
      MONGO_PORT: "27017"
    user: worker
    working_dir: /home/worker/case
    volumes:
      - .:/home/worker/case
      - ../../../data:/home/worker/tesp/data
    networks:
      cst_net:
        ipv4_address: 10.5.0.5
    command: /bin/bash -c "source /home/worker/venv/bin/activate && exec python3 -c \"import cosim_toolbox.federateLogger as datalog; datalog.main('FederateLogger', 'HelicsExampleDefaultSchema', 'HelicsExampleDefault')\""
networks:
  cst_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
