name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: login to hub
        env:
          API_KEY: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "Using API key $API_KEY"
        # echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          
      - name: Build and Publish
        run: |
          cd
          source ./cosim.env
          cd scripts/docker
        # ./build_publish_images.sh
          
      - name: Test
        run: |
          cd
          source ./cosim.env
          cd scripts/docker
        # ./intergration_test.sh

